name: Playwright Tests
on:
  push: { branches: [main, master] }
  pull_request: { branches: [main, master] }

jobs:
  test:
    runs-on: windows-latest
    timeout-minutes: 60
    env:
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm ci
      - run: npx playwright test --project="Microsoft Edge"
      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
